# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# This is to expose the vite server port.
services:
  web:
    expose:
      - '5173'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,5172:5173
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,5173:5173